[tool.poetry]
name = "Tower_game"
version = "0.1.0"
description = ""
authors = [
    "Voronwe <mail@voronwe.me>",
    "Hairash <maslevian@yandex.ru>",
]

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.5"

[build-system]
requires = ["poetry>=1.8"]
build-backend = "poetry.masonry.api"
